# **PROYECTO FINAL DE ANÁLISIS DE DATOS NIVEL EXPLORADOR**

Este proyecto final tiene como objetivo evaluar los conocimientos adquiridos en el Nivel 1 del curso de análisis de datos.

## ***Objetivo del Proyecto:***
Desarrollar un análisis exhaustivo de datos reales para abordar una
problemática identificada en el contexto de la transición energética o las TIC.  El proyecto busca demuestrar nuestra capacidad para explorar, limpiar, manipular, y visualizar datos, interpretando patrones y tendencias para llegar a conclusiones
significativas.

## **Descripción del Proyecto:**

### **1. Identificación de la Problemática:**
- Desarrollar un análisis de datos reales para abordar una problemática identificada en el contexto del acompañamiento integral para hogares víctimas de desplazamiento forzado por el conflicto armado en zonas rurales.

- Enfoque: Incluye el retorno o reubicación, apoyo a iniciativas productivas, fortalecimiento del liderazgo comunitario y mejora de las condiciones de habitabilidad, con el objetivo de mejorar las condiciones de vida de estos hogares.

2. Recolección de Datos:
- Obtener datos públicos y verídicos relacionados con el programa Familias en su Tierra que es un esquema especial de acompañamiento familiar implementado por el Gobierno Nacional, a través de Prosperidad Social.
- Los datos fueron extraídos de "Datos abiertos Colombia", enlace: https://www.datos.gov.co/Inclusi-n-Social-y-Reconciliaci-n/Beneficiarios-Familias-en-su-tierra/mebh-t5gy

3. Exploración y Limpieza de Datos:
- Cargar los datos en Python utilizando bibliotecas como Pandas y Numpy.
- Realizar una exploración inicial para entender la estructura y el contenido de los datos.
- Identificar y manejar valores faltantes, datos atípicos, y errores en los datos.
- Aplicar técnicas de limpieza para asegurar la calidad de los datos antes de proceder al análisis.

4. Análisis Descriptivo:
- Utilizar técnicas de análisis descriptivo para identificar patrones, tendencias, y distribuciones en los datos.
- Calcular medidas de tendencia central, varianza, percentiles, y otros estadísticos relevantes.
- Visualizar los datos mediante gráficos y diagramas usando Matplotlib.

5. Interpretación de Resultados:
- Interpretar los resultados obtenidos del análisis descriptivo.
- Identificar conclusiones clave que aborden la problemática seleccionada.
- Discutir las implicaciones de los hallazgos y cómo podrían influir en la toma de decisiones relacionadas con la problemática.

6. Documentación del Proyecto:
- Redactar un informe que detalle todo el proceso, desde la identificación de la problemática hasta la interpretación de los resultados.
- Incluir una introducción, descripción del problema, metodología, análisis de datos, resultados, conclusiones, y recomendaciones.

In [2]:
# 1. Importar la librería Pandas
import pandas as pd
import matplotlib.pyplot as plt

# 2. Leer el archivo CSV Beneficiarios_Familias_en_su_tierra_20251028.csv
# Por ahora la ruta estará en el drive personal, pero deberá quedar en el repositorio
#  https://github.com/nepmovistar-cmyk/ProyectoPYTHON/raw/refs/heads/main/Beneficiarios_Familias_en_su_tierra.rar

ruta = '/content/drive/MyDrive/Colab Notebooks/Proyecto_Final_Bootcamp2025/DataCol_Beneficiarios_Familias_en_su_tierra.csv'
df = pd.read_csv(ruta)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365494 entries, 0 to 365493
Data columns (total 25 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   CantidadDeBeneficiarios                 365494 non-null  int64
 1   CantidadBeneficioConsolidado            365494 non-null  int64
 2   CantidadUltimobeneficio                 365494 non-null  int64
 3   CodigoDepartamentoAtencion              365494 non-null  int64
 4   CodigoMunicipioAtencion                 365494 non-null  int64
 5   CondicionSexual                         365494 non-null  object
 6   Discapacidad                            365494 non-null  object
 7   EstadoBeneficiario                      365494 non-null  object
 8   EstadoCivil                             365494 non-null  object
 9   Etnia                                   365494 non-null  object
 10  FechaInscripcionBeneficiario            365494 non-null  object
 11  FechaUltimoBeneficioAsignado            365494 non-null  object
 12  Genero                                  365494 non-null  object
 13  NivelEscolaridad                        365494 non-null  object
 14  NombreDepartamentoAtencion              365494 non-null  object
 15  NombreMunicipioAtencion                 365494 non-null  object
 16  Pais                                    365494 non-null  object
 17  Parentesco                              365494 non-null  object
 18  RangoEdad                               365494 non-null  object
 19  TipoAsignacionBeneficio                 365494 non-null  object
 20  TipoBeneficio                           365494 non-null  object
 21  TipoDocumento                           365494 non-null  object
 22  TipoPoblacion                           365494 non-null  object
 23  RangoValorBeneficioConsolidadoAsignado  365494 non-null  object
 24  RangoValorUltimoBeneficioAsignado       365494 non-null  object
dtypes: int64(5), object(20)
memory usage: 69.7+ MB

In [ ]:
# 3. Ver las primeras filas del DataFrame
# se pausa esta instrucción por temas de memoria al ejecutar en el entorno
#display(df)
df.head()

,CantidadDeBeneficiarios,CantidadBeneficioConsolidado,CantidadUltimobeneficio,CodigoDepartamentoAtencion,CodigoMunicipioAtencion,CondicionSexual,Discapacidad,EstadoBeneficiario,EstadoCivil,Etnia,...,NombreMunicipioAtencion,Pais,Parentesco,RangoEdad,TipoAsignacionBeneficio,TipoBeneficio,TipoDocumento,TipoPoblacion,RangoValorBeneficioConsolidadoAsignado,RangoValorUltimoBeneficioAsignado
0,1,2,1,25,25394,Heterosexual,NO,NO ACTIVO,SO,ND,...,LA PALMA,COLOMBIA,ND,>65,RURAL,MONETARIO Y EN ESPECIE,CC,DESPLAZADOS,1.500.001 - 3.000.000,0 - 1.300.000
1,1,1,1,47,47551,Heterosexual,NO,ATENDIDO,CA,ND,...,PIVIJAY,Colombia,Jefe del hogar,30-49,INCENTIVO IDEA PRODUCTIVA,INCENTIVO DE IDEA PRODUCTIVA,CC,DESPLAZADOS,1.500.001 - 3.000.000,1.300.001 - 2.600.000
2,1,4,1,5,5660,ND,ND,ACTIVO,ND,ND,...,SAN LUIS,169,ND,>65,RURAL,MONETARIO Y EN ESPECIE,CC,AMBAS CONDICIONES,4.500.001 - 6.000.000,2.600.001 - 3.900.000
3,1,3,1,50,50251,ND,ND,ACTIVO,ND,ND,...,EL CASTILLO,169,ND,>65,RURAL,MONETARIO Y EN ESPECIE,CC,AMBAS CONDICIONES,3.000.001 - 4.500.000,1.300.001 - 2.600.000
4,1,4,1,5,5045,Heterosexual,NO,NO ACTIVO,ND,ND,...,APARTADO,COLOMBIA,ND,>65,RURAL,MONETARIO Y EN ESPECIE,CC,AMBAS CONDICIONES,4.500.001 - 6.000.000,2.600.001 - 3.900.000

In [ ]:
df.EstadoBeneficiario.unique()

array(['NO ACTIVO', 'ATENDIDO', 'ACTIVO', 'RETIRADO',
       'VINCULADO-INSCRITO', 'FALLECIDO'], dtype=object)

In [ ]:
df.EstadoCivil.unique()
#df.Genero.unique()

array(['H-HOMBRE', 'Heterosexual', 'ND', 'M-MUJER', 'Gay', 'H', 'M',
       'Bisexual', 'No responde', 'SIN ESPECIFICAR', 'M-Mujer',
       'Lesbiana', 'HOMBRE'], dtype=object)

In [ ]:
# Contar cuántos valores hay de cada tipo:
df['CondicionSexual'].value_counts()

CondicionSexual
Heterosexual       270253
ND                  53441
No responde         18398
H-HOMBRE            13658
M-MUJER              7907
Bisexual             1279
H                     214
M                     162
Lesbiana               99
Gay                    57
SIN ESPECIFICAR        14
M-Mujer                10
HOMBRE                  2
Name: count, dtype: int64

In [ ]:
# Unificar columna "CondicionSexual" cuyo dato es igual a "H", "HOMBRE" y "H-HOMBRE" a "Heterosexual"
df.loc[df['CondicionSexual'] == 'H', 'CondicionSexual'] = 'Heterosexual'
df.loc[df['CondicionSexual'] == 'HOMBRE', 'CondicionSexual'] = 'Heterosexual'
df.loc[df['CondicionSexual'] == 'H-HOMBRE', 'CondicionSexual'] = 'Heterosexual'

# Unificar columna "CondicionSexual" cuyo dato es igual a "M", "M-MUJER" y "M-Mujer" a "Heterosexual"
df.loc[df['CondicionSexual'] == 'M', 'CondicionSexual'] = 'Heterosexual'
df.loc[df['CondicionSexual'] == 'M-MUJER', 'CondicionSexual'] = 'Heterosexual'
df.loc[df['CondicionSexual'] == 'M-Mujer', 'CondicionSexual'] = 'Heterosexual'

In [ ]:
df['CondicionSexual'].value_counts()

CondicionSexual
Heterosexual       292206
ND                  53441
No responde         18398
Bisexual             1279
Lesbiana               99
Gay                    57
SIN ESPECIFICAR        14
Name: count, dtype: int64

In [ ]:
df.to_csv('/content/drive/MyDrive/Colab Notebooks/Proyecto_Final_Bootcamp2025/Beneficiarios_Familias_en_su_tierra.csv', index=False)

In [ ]:
df.EstadoCivil.unique()

array(['SO', 'Casado(a)', 'ND', 'CA', 'Unión libre', 'UL', 'VI',
       'Soltero(a)', 'DI', 'Viudo(a)', 'NO REPORTA', 'DIVORCIADO(A)',
       'Sin Informació', 'Separado(a) o', 'VIVE EN PAREJA'], dtype=object)

In [ ]:
df['EstadoCivil'].value_counts()

EstadoCivil
Soltero(a)        112548
Unión libre       105702
Casado(a)          37997
Sin Informació     33839
Separado(a) o      16632
NO REPORTA         13553
ND                 12438
Viudo(a)           10652
UL                  7239
CA                  5193
SO                  4664
DIVORCIADO(A)       2230
VI                  1308
DI                  1220
VIVE EN PAREJA       279
Name: count, dtype: int64

In [ ]:
# Unificar columna "EstadoCivil"
df.loc[df['EstadoCivil'] == 'Casado(a)', 'EstadoCivil'] = 'CA'
df.loc[df['EstadoCivil'] == 'Soltero(a)', 'EstadoCivil'] = 'SO'
df.loc[df['EstadoCivil'] == 'DIVORCIADO(A)', 'EstadoCivil'] = 'DI'
df.loc[df['EstadoCivil'] == 'Viudo(a)', 'EstadoCivil'] = 'VI'
df.loc[df['EstadoCivil'] == 'Unión libre', 'EstadoCivil'] = 'UL'
df.loc[df['EstadoCivil'] == 'Separado(a) o', 'EstadoCivil'] = 'DI'
df.loc[df['EstadoCivil'] == 'VIVE EN PAREJA', 'EstadoCivil'] = 'UL'
df.loc[df['EstadoCivil'] == 'NO REPORTA', 'EstadoCivil'] = 'ND'
df['EstadoCivil'].value_counts()

EstadoCivil
SO                117212
UL                113220
CA                 43190
Sin Informació     33839
ND                 25991
DI                 20082
VI                 11960
Name: count, dtype: int64

In [ ]:
df.to_csv('/content/drive/MyDrive/Colab Notebooks/Proyecto_Final_Bootcamp2025/Beneficiarios_Familias_en_su_tierra.csv', index=False)

In [ ]:
df.Etnia.unique()

array(['ND', 'AFROCOLOMBIANO – NEGRO', 'INDIGENA', 'PALENQUERO', 'RAIZAL',
       'ROM O GITANO', 'MESTIZO'], dtype=object)

In [ ]:
# Unificar columna "Etnia"
df.loc[df['Etnia'] == 'AFROCOLOMBIANO - NEGRO', 'Etnia'] = 'AFROCOLOMBIANO – NEGRO'
df.loc[df['Etnia'] == 'Indígena', 'Etnia'] = 'INDIGENA'
df.loc[df['Etnia'] == 'ROM', 'Etnia'] = 'ROM O GITANO'
df.loc[df['Etnia'] == 'SIN ESPECIFICAR', 'Etnia'] = 'ND'

In [ ]:
df['Etnia'].value_counts() by

Etnia
ND                        346191
AFROCOLOMBIANO – NEGRO     12326
Indígena                    3667
INDIGENA                    2220
RAIZAL                       565
PALENQUERO                   229
ROM O GITANO                 174
ROM                           75
MESTIZO                       29
SIN ESPECIFICAR               14
AFROCOLOMBIANO - NEGRO         4
Name: count, dtype: int64

In [ ]:
df.head()

,CantidadDeBeneficiarios,CantidadBeneficioConsolidado,CantidadUltimobeneficio,CodigoDepartamentoAtencion,CodigoMunicipioAtencion,CondicionSexual,Discapacidad,EstadoBeneficiario,EstadoCivil,Etnia,...,NombreMunicipioAtencion,Pais,Parentesco,RangoEdad,TipoAsignacionBeneficio,TipoBeneficio,TipoDocumento,TipoPoblacion,RangoValorBeneficioConsolidadoAsignado,RangoValorUltimoBeneficioAsignado
0,1,2,1,25,25394,Heterosexual,NO,NO ACTIVO,SO,ND,...,LA PALMA,COLOMBIA,ND,>65,RURAL,MONETARIO Y EN ESPECIE,CC,DESPLAZADOS,1.500.001 - 3.000.000,0 - 1.300.000
1,1,1,1,47,47551,Heterosexual,NO,ATENDIDO,CA,ND,...,PIVIJAY,Colombia,Jefe del hogar,30-49,INCENTIVO IDEA PRODUCTIVA,INCENTIVO DE IDEA PRODUCTIVA,CC,DESPLAZADOS,1.500.001 - 3.000.000,1.300.001 - 2.600.000
2,1,4,1,5,5660,ND,ND,ACTIVO,ND,ND,...,SAN LUIS,169,ND,>65,RURAL,MONETARIO Y EN ESPECIE,CC,AMBAS CONDICIONES,4.500.001 - 6.000.000,2.600.001 - 3.900.000
3,1,3,1,50,50251,ND,ND,ACTIVO,ND,ND,...,EL CASTILLO,169,ND,>65,RURAL,MONETARIO Y EN ESPECIE,CC,AMBAS CONDICIONES,3.000.001 - 4.500.000,1.300.001 - 2.600.000
4,1,4,1,5,5045,Heterosexual,NO,NO ACTIVO,ND,ND,...,APARTADO,COLOMBIA,ND,>65,RURAL,MONETARIO Y EN ESPECIE,CC,AMBAS CONDICIONES,4.500.001 - 6.000.000,2.600.001 - 3.900.000

In [ ]:
df['NombreMunicipioAtencion'].value_counts()

NombreMunicipioAtencion
TIBÚ               6157
TIERRALTA          5960
MUTATÁ             5035
AGUSTÍN CODAZZI    5012
MOCOA              4879
                   ...
LA ESTRELLA           2
GACHALA               2
VILLETA               2
TORIBIO               2
CIUDAD BOLIVAR        1
Name: count, Length: 647, dtype: int64

In [ ]:
df['NombreDepartamentoAtencion'].value_counts()

NombreDepartamentoAtencion
ANTIOQUIA             48013
BOLIVAR               33812
PUTUMAYO              27691
CESAR                 23957
NARIÑO                23908
SUCRE                 22007
NORTE DE SANTANDER    20291
CÓRDOBA               19093
MAGDALENA             16633
CHOCO                 16559
META                  16362
CAUCA                 14918
CAQUETA               12997
LA GUAJIRA            12902
TOLIMA                12008
CALDAS                 8322
ARAUCA                 6348
CUNDINAMARCA           5743
VALLE DEL CAUCA        5306
RISARALDA              3987
SANTANDER              3537
GUAVIARE               3052
HUILA                  2800
CASANARE               1356
CORDOBA                1239
BOGOTA                 1052
VALLE                   663
AMAZONAS                579
ATLANTICO               272
QUINDIO                  46
BOYACA                   41
Name: count, dtype: int64

In [ ]:
# Unificar columna "NombreDepartamentoAtencion"
df.loc[df['NombreDepartamentoAtencion'] == 'VALLE', 'NombreDepartamentoAtencion'] = 'VALLE DEL CAUCA'

In [ ]:
df.head()

,CantidadDeBeneficiarios,CantidadBeneficioConsolidado,CantidadUltimobeneficio,CodigoDepartamentoAtencion,CodigoMunicipioAtencion,CondicionSexual,Discapacidad,EstadoBeneficiario,EstadoCivil,Etnia,...,NombreMunicipioAtencion,Pais,Parentesco,RangoEdad,TipoAsignacionBeneficio,TipoBeneficio,TipoDocumento,TipoPoblacion,RangoValorBeneficioConsolidadoAsignado,RangoValorUltimoBeneficioAsignado
0,1,2,1,25,25394,Heterosexual,NO,NO ACTIVO,SO,ND,...,LA PALMA,COLOMBIA,ND,>65,RURAL,MONETARIO Y EN ESPECIE,CC,DESPLAZADOS,1.500.001 - 3.000.000,0 - 1.300.000
1,1,1,1,47,47551,Heterosexual,NO,ATENDIDO,CA,ND,...,PIVIJAY,Colombia,Jefe del hogar,30-49,INCENTIVO IDEA PRODUCTIVA,INCENTIVO DE IDEA PRODUCTIVA,CC,DESPLAZADOS,1.500.001 - 3.000.000,1.300.001 - 2.600.000
2,1,4,1,5,5660,ND,ND,ACTIVO,ND,ND,...,SAN LUIS,169,ND,>65,RURAL,MONETARIO Y EN ESPECIE,CC,AMBAS CONDICIONES,4.500.001 - 6.000.000,2.600.001 - 3.900.000
3,1,3,1,50,50251,ND,ND,ACTIVO,ND,ND,...,EL CASTILLO,169,ND,>65,RURAL,MONETARIO Y EN ESPECIE,CC,AMBAS CONDICIONES,3.000.001 - 4.500.000,1.300.001 - 2.600.000
4,1,4,1,5,5045,Heterosexual,NO,NO ACTIVO,ND,ND,...,APARTADO,COLOMBIA,ND,>65,RURAL,MONETARIO Y EN ESPECIE,CC,AMBAS CONDICIONES,4.500.001 - 6.000.000,2.600.001 - 3.900.000

In [ ]:
df['Pais'].value_counts()

Pais
Colombia    317084
ND           29882
COLOMBIA     18151
169            373
57               4
Name: count, dtype: int64

In [ ]:
# Unificar columna "Pais"
df.loc[df['Pais'] == 'COLOMBIA', 'Pais'] = 'Colombia'
df.loc[df['Pais'] == '169', 'Pais'] = 'Colombia'
df.loc[df['Pais'] == '57', 'Pais'] = 'Colombia'

In [ ]:
df['Pais'].value_counts()

Pais
Colombia    335612
ND           29882
Name: count, dtype: int64